# Generated by Django 5.2.8 on 2025-11-30 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commerce_order', models.CharField(max_length=64, unique=True)),
                ('flow_token', models.CharField(blank=True, max_length=128, null=True)),
                ('flow_order', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='CLP', max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('created', 'Creada'), ('paid', 'Pagada'), ('canceled', 'Cancelada'), ('error', 'Error')], default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
