# Generated by Django 5.2.8 on 2025-12-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_shipping_ciudad_order_shipping_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('editorial', models.CharField(blank=True, max_length=255, null=True)),
                ('binding', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('price_old', models.IntegerField(blank=True, null=True)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=64, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
