# Generated by Django 5.2.8 on 2025-12-02 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Despacho'), ('billing', 'Cobranza')], default='shipping', max_length=16, verbose_name='Tipo de dirección'),
        ),
        migrations.AlterField(
            model_name='address',
            name='ciudad',
            field=models.CharField(max_length=64, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='comuna',
            field=models.CharField(max_length=64, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Predeterminada'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=128, verbose_name='Dirección (calle y número)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Depto / bloque (opcional)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nombre receptor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=64, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Encuadernación'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensiones'),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen (URL)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Páginas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_old',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio anterior'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sku',
            field=models.CharField(max_length=64, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiquetas (separadas por coma)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de edición'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commerce_order',
            field=models.CharField(max_length=64, unique=True, verbose_name='Orden de comercio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='CLP', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email comprador'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flow_order',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Orden Flow'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flow_token',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Token Flow'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_ciudad',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_comuna',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_line1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección (calle y número)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_line2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Depto / bloque (opcional)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre receptor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono receptor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_region',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Creada'), ('paid', 'Pagada'), ('canceled', 'Cancelada'), ('error', 'Error')], default='created', max_length=16, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
