# Generated by Django 5.2.8 on 2025-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_address_address_type_alter_address_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_item_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
