# Generated by Django 5.2.8 on 2025-12-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_first_item_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_ciudad',
        ),
    ]
