# Generated by Django 5.2.8 on 2026-06-10 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_coupon_code_couponredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price_at_purchase', models.IntegerField(verbose_name='Precio al momento de compra')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.book', verbose_name='Libro')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Orden')),
            ],
        ),
    ]
