# Generated by Django 5.2.8 on 2026-08-29 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT')),
                ('doc_type', models.CharField(default='RUT', max_length=20, verbose_name='Tipo de documento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
