# Generated by Django 5.2.8 on 2026-08-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(choices=[('preparando', 'Preparando Pedido'), ('en_camino', 'En Camino'), ('entregado', 'Entregado')], default='preparando', max_length=20, verbose_name='Estado de seguimiento'),
        ),
    ]
